### ISSUE TITLE
create_table_help

### ISSUE THREAD

**Issue by UlkaBo** [starperov-net/universal_flash_cards_chatbot#163]
epic {#152}
створити таблицю help
columns :
state help language
"study" "read books" English
"study" "читай книжки" Ukrainian

+ міграція

**Comment by Romanskyy** [comment]
@UlkaBo  может используем state(состояние, положение, статус) вместо stage(этап, стадия, ступень)?

**Comment by Romanskyy** [comment]
Это не спор) высказываю мнение

почему бы не создать две таблицы вместо одной?

1. Help -> где будет <state>, <help_text>
2. Help_translation -> где будет <help_id>, <context_id>,  <translated_help>
