### ISSUE TITLE
show_help

### ISSUE THREAD

**Issue by UlkaBo** [starperov-net/universal_flash_cards_chatbot#166]
epic {#152}
Викликається /help
Зробити запит в help
функція спочатку шукає в цій таблиці help мовою юзера, якщо нема, то перекладає google translate і додає в цю таблицю новий рядок.
Додати внизу кнопку, після натискання, сховати message с help.

**Comment by YanaAnisimova** [comment]
`Додати внизу кнопку, після натискання, сховати message с help.` - для чого це робити?

**Comment by UlkaBo** [comment]
щоб воно не засмічувало стрічку.
Для удобства та красоти.

**Comment by YanaAnisimova** [comment]
давай поки робити не буду, подивимось на скільки воно буде засмічувати стрічку. якщо рішемо, що кнопка потрібна, додамо
