### ISSUE TITLE
create keyboard from list of words for epic list

### ISSUE THREAD

**Issue by UlkaBo** [starperov-net/universal_flash_cards_chatbot#170]
{#108}
для epic show user's train list
input_data : list of words
return: keyboard

Повинен передавати в callbackData card.id 

Далі має з'явитись дві кнопки під натиснутою кнопкою - edit, delete , але це вже інша функція.

**Comment by UlkaBo** [comment]
Застосувати пагинацію

**Comment by YanaAnisimova** [comment]
SUBTASK:

- [ ] #175
