### ISSUE TITLE
create handler study_words

### ISSUE THREAD

**Issue by UlkaBo** [starperov-net/universal_flash_cards_chatbot#50]
input : /study , state

call function create_list_cards_for_study
for word in list_cars:
    state.first()
   answer with item_random and keyboard "know", "don't know"

use spoiler text
if this is possible
 answer with item_random
 answer with item_other_side with keyboard "know", "don't know"

**Comment by Romanskyy** [comment]
@YanaAnisimova 
итак это кнопка и она должна быть как бы под тремя кнопками которые у вас уже есть?

**Comment by YanaAnisimova** [comment]
нет, это не кнопка, а команда (как `/start` в меню)

**Comment by YanaAnisimova** [comment]
По поводу state в input, пока он не нужен.

**Comment by YanaAnisimova** [comment]
Хердлер должен реагировать на команду `/study`, который будет выводить по очереди слова (card) c заблюренным переводом и клавиатурой с "know", "don't know" (данная клавиатура уже у нас есть). Для получения списка cards есть функция `get_list_cards_to_study_db`.

**Comment by Romanskyy** [comment]
команда и кнопка это разный функционал, я так понимаю?

**Comment by YanaAnisimova** [comment]
да, пример команды - хендлер `start`
