### ISSUE TITLE
develop translate algorythm

### ISSUE THREAD

**Issue by KonstZiv** [starperov-net/universal_flash_cards_chatbot#78]

**Comment by KonstZiv** [comment]
Розробка алгоритму отримання перекладу по запиту користувача в умовах вільного вводу слова (без попереднього визначення мови) і врахування можливостей:
- помилки користувача при вводі слова (ввів чорті-шо)
- відповіді GOOGL і визначення мови запиту (визначив мову слова для перекладу як не ту, яку ми мали на увазі)

**Comment by KonstZiv** [comment]
Результат

**Comment by UlkaBo** [comment]
Це ж загальний опис алгоритма?
Там буде трохи більше запитів та умов.
